package com.lifeccp.domain;

import javax.persistence.*;

/**
 * Created by Star on 2015/9/14.
 */
@MappedSuperclass
public class BasicDomain {
    // ==============
    // PRIVATE FIELDS
    // ==============
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    public Integer id;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
}
